backend:
  name: github
  repo: jasonpbenson/elgv2_gatsbynetlify
  branch: master

media_folder: "static/img"
public_folder: "img"
site_url: "https://enchanted-life-goods.us/"
display_url: "https://enchanted-life-goods.us/"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "goods"
    label: "Goods"
    folder: "src/markdown-pages/goods"
    create: true
    extention: md
    slug: "{{type}}_{{title}}"
    fields:
      - {
          name: "templateKey",
          label: "Template Key",
          widget: "hidden",
          default: "good",
        }
      - { name: "image1", label: "Image 1", widget: "image" }
      - { name: "image1-alt", label: "Image 1 Alt", widget: "string" }
      - { name: "image2", label: "Image 2", widget: "image" }
      - { name: "image2-alt", label: "Image 2 Alt", widget: "string" }
      - { name: "image3", label: "Image 3", widget: "image" }
      - { name: "image3-alt", label: "Image 3 Alt", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "type", label: "Type", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - { label: "Path", name: "path", widget: string }
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Title", name: "title", widget: string }
          - { label: "Logo", name: "logo", widget: image }
